# Generated by Django 4.2.1 on 2023-05-15 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likes_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follow_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 17, 5, 7, 323138)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 17, 5, 7, 321138)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 17, 5, 7, 321138)),
        ),
    ]
