# Generated by Django 4.2.1 on 2023-05-17 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follower_like_remove_likes_post_remove_likes_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followers',
            new_name='follows',
        ),
        migrations.AlterField(
            model_name='follower',
            name='follow_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 13, 12, 18, 89961)),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 13, 12, 18, 88961)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 13, 12, 18, 88961)),
        ),
    ]
