# Generated by Django 4.1.5 on 2023-02-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentBid', models.IntegerField()),
                ('bidIncrement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingTitle', models.CharField(max_length=64)),
                ('listingDescription', models.CharField(max_length=512)),
                ('startBid', models.IntegerField()),
                ('imageURL', models.URLField()),
                ('listingCategory', models.CharField(max_length=64)),
            ],
        ),
    ]
