# Generated by Django 4.1.5 on 2023-02-17 14:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentText',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
