# Generated by Django 4.1.5 on 2023-02-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='currentBidUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
