# Generated by Django 4.1.5 on 2023-02-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_bidlisting_bid_currentbiduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='startBid',
        ),
        migrations.AddField(
            model_name='bid',
            name='startBid',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidIncrement',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidListing',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
