# Generated by Django 4.1.5 on 2023-02-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidIncrement',
        ),
    ]
