# Generated by Django 4.1.5 on 2023-02-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bid_bidincrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='bid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
