# Generated by Django 4.2.1 on 2023-06-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newTab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newTab.block')),
                ('colour', models.CharField(default='#0000FF', max_length=7)),
                ('timeScale', models.IntegerField(default=1)),
            ],
            bases=('newTab.block',),
        ),
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='block',
            name='startTime',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.CharField(default='Block', max_length=64),
        ),
        migrations.AddField(
            model_name='routine',
            name='name',
            field=models.CharField(default='Routine', max_length=64),
        ),
        migrations.AddField(
            model_name='routine',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newTab.block')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newTab.parentblock')),
            ],
            bases=('newTab.block',),
        ),
        migrations.AddField(
            model_name='parentblock',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newTab.routine'),
        ),
    ]
